---
# # # # # # # # # #
#  A L W A Y S 
#      B E
# C A S T I N G
# # # # # # # # # #

# Basic
name: "Always Be Casting"
description: ""

# URL
url: "http://always-be-casting.github.io"
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "reference"
   href: "/ref"

 - name: "contact"
   href: "mailto:alwaysbecasting1@gmail.com"

# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
